previews:
  generation: manual
  expireAfterDays: 3

services:
  - type: web
    name: ssi-scoring
    runtime: node
    plan: starter
    branch: main
    repo: https://github.com/tohewi/tapahtumakalenteri-ssi-integrator
    previews:
      plan: starter
    buildCommand: cd scoring-ui && npm ci && npm run build && cd ../scoring-proxy && npm ci
    startCommand: cd scoring-proxy && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
