# Kupittaa Reservilaisammunta induction wait list configuration

adminAllowlist:
  - "tohewi@live.com"

ssiUserValidation:
  groupId: "26740"

induction:
  threshold: 5

routes:
  publicPath: "#/induction-waitlist"
  adminPath: "#/induction-waitlist-admin"

notifications:
  fromName: "TurRes Wait List"
  supportedLanguages:
    - fi
    - en
